name: depcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      # Install dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
      - run: npm install -g "yarn@1.22.5"
      - uses: actions/cache@v2
        name: Restore Yarn cache.
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.cjs
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-
      - run: yarn install --immutable
        name: Install yarn dependencies

      # Run depcheck
      - name: Run depcheck
        run: |
          yarn depcheck
